[package]
name = "hiero-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-openai.workspace = true
async-trait.workspace = true
chrono.workspace = true
csv.workspace = true
lancedb.workspace = true
ort.workspace = true
phf.workspace = true
pulldown-cmark.workspace = true
regex.workspace = true
reqwest.workspace = true
rust-embed.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
sqlx.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
uuid.workspace = true

[lints]
workspace = true
