//! Per-user daemon service management (`hiero service …`, security design
//! spec §Service Installation): one systemd **user** unit rendered from the
//! absolute installed binary and the explicit data root, with a restart/backoff
//! policy and a stable log identifier. Install, upgrade, and uninstall are
//! idempotent and never touch user data.
//!
//! Manager integration rules (this is the test seam too): the systemd user
//! manager is only ever contacted when the unit lives at the default location
//! (`~/.config/systemd/user`) and `systemctl` exists on `PATH`. An explicit
//! `--unit-dir` override means the caller owns the manager interaction, so
//! `install`/`uninstall` only render or remove the unit file and report it —
//! which keeps tests away from the real user manager and makes custom
//! locations usable on non-systemd setups.

use std::path::{Path, PathBuf};
use std::process::Command;

/// Name of the unit this project installs.
pub const SERVICE_UNIT_NAME: &str = "hieronymus.service";

/// Seconds between daemon restart attempts (on-failure backoff policy).
const RESTART_SECONDS: &str = "5s";

#[derive(Debug, thiserror::Error)]
pub enum ServiceError {
    #[error("{0}")]
    Manager(String),
    #[error("{0}")]
    Invalid(String),
    #[error(transparent)]
    Io(#[from] std::io::Error),
}

/// Everything one service subcommand needs: the data root to serve, the unit
/// directory, the binary the unit must exec, and whether manager integration
/// is allowed at all (CLI `--no-activate` sets it to `false`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceOptions {
    pub data_root: PathBuf,
    pub unit_dir: PathBuf,
    pub binary: PathBuf,
    pub use_manager: bool,
}

impl ServiceOptions {
    pub fn unit_path(&self) -> PathBuf {
        self.unit_dir.join(SERVICE_UNIT_NAME)
    }
}

/// Default per-user unit directory (systemd user units).
pub fn default_unit_dir() -> PathBuf {
    home::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".config")
        .join("systemd")
        .join("user")
}

/// Whether the systemd user manager may be contacted for these options: only
/// when manager use is allowed, the unit lives at the default location, and
/// `systemctl` exists on `PATH`.
pub fn manager_enabled(options: &ServiceOptions) -> bool {
    options.use_manager && options.unit_dir == default_unit_dir() && systemctl_on_path()
}

fn systemctl_on_path() -> bool {
    std::env::var_os("PATH")
        .map(|path| {
            std::env::split_paths(&path).any(|directory| directory.join("systemctl").is_file())
        })
        .unwrap_or(false)
}

fn run_systemctl(arguments: &[&str]) -> Result<(), ServiceError> {
    let output = Command::new("systemctl")
        .arg("--user")
        .args(arguments)
        .output()
        .map_err(|error| ServiceError::Manager(format!("could not run systemctl: {error}")))?;
    if output.status.success() {
        return Ok(());
    }
    Err(ServiceError::Manager(format!(
        "systemctl --user {} failed: {}",
        arguments.join(" "),
        String::from_utf8_lossy(&output.stderr).trim()
    )))
}

/// The unit file content for one binary/data-root pair. Deterministic, so an
/// idempotent reinstall is byte-identical. Both paths are double-quoted;
/// systemd accepts quoted ExecStart arguments and the parser here mirrors it.
pub fn render_unit(binary: &Path, data_root: &Path) -> Result<String, ServiceError> {
    let binary = absolute(binary)?;
    let data_root = absolute(data_root)?;
    for (label, path) in [("binary", &binary), ("data root", &data_root)] {
        let text = path.to_str().ok_or_else(|| {
            ServiceError::Invalid(format!(
                "{label} path is not valid UTF-8: {}",
                path.display()
            ))
        })?;
        if text.contains(['"', '\\', '\n']) {
            return Err(ServiceError::Invalid(format!(
                "{label} path contains a quote, backslash, or newline, which the unit \
                 renderer does not support: {text}"
            )));
        }
    }
    Ok(format!(
        "# Generated by `hiero service install` — manual edits are overwritten by \
         the next install or update.\n\
         [Unit]\n\
         Description=Hieronymus translation memory daemon\n\
         After=network.target\n\
         \n\
         [Service]\n\
         ExecStart=\"{binary}\" daemon --data-root \"{data_root}\"\n\
         Restart=on-failure\n\
         RestartSec={RESTART_SECONDS}\n\
         SyslogIdentifier=hieronymus-daemon\n\
         NoNewPrivileges=true\n\
         PrivateTmp=true\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        binary = binary.display(),
        data_root = data_root.display(),
    ))
}

fn absolute(path: &Path) -> Result<PathBuf, ServiceError> {
    if path.is_absolute() {
        Ok(path.to_path_buf())
    } else {
        Err(ServiceError::Invalid(format!(
            "path must be absolute (the unit may not rely on the daemon's working \
             directory): {}",
            path.display()
        )))
    }
}

/// The parsed execution definition of one unit file, as far as this project
/// renders and reads them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnitDefinition {
    pub binary: PathBuf,
    pub data_root: PathBuf,
}

/// Parse `ExecStart="…" daemon --data-root "…"` out of a unit file. Returns
/// `Err` with a reason when the unit is not one of ours or is broken.
pub fn parse_unit(text: &str) -> Result<UnitDefinition, String> {
    let line = text
        .lines()
        .find(|line| line.starts_with("ExecStart="))
        .ok_or("unit file has no ExecStart entry")?;
    let tokens = tokenize(&line["ExecStart=".len()..]);
    match tokens.as_slice() {
        [binary, command, flag, data_root] if command == "daemon" && flag == "--data-root" => {
            Ok(UnitDefinition {
                binary: PathBuf::from(binary),
                data_root: PathBuf::from(data_root),
            })
        }
        _ => Err("unit ExecStart is not `\"<binary>\" daemon --data-root \"<root>\"`".to_string()),
    }
}

/// Split a systemd ExecStart argument list on spaces, honoring double quotes.
fn tokenize(input: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut current = String::new();
    let mut quoted = false;
    for character in input.chars() {
        match character {
            '"' => quoted = !quoted,
            ' ' if !quoted => {
                if !current.is_empty() {
                    tokens.push(std::mem::take(&mut current));
                }
            }
            other => current.push(other),
        }
    }
    if !current.is_empty() {
        tokens.push(current);
    }
    tokens
}

/// Read and parse the unit file for `options`, if it exists.
pub fn read_unit(options: &ServiceOptions) -> Result<Option<UnitDefinition>, String> {
    let path = options.unit_path();
    if !path.exists() {
        return Ok(None);
    }
    let text = std::fs::read_to_string(&path)
        .map_err(|error| format!("could not read {}: {error}", path.display()))?;
    parse_unit(&text)
        .map(Some)
        .map_err(|reason| format!("{}: {reason}", path.display()))
}

/// Install (or idempotently reinstall) the unit. The unit file is written
/// atomically; the manager, when engaged, is reloaded and the unit enabled
/// **without starting it** — the start decision belongs to the caller after
/// the schema check (bootstrap installer step 8).
pub fn install(options: &ServiceOptions) -> Result<Vec<String>, ServiceError> {
    let mut lines = Vec::new();
    if !options.binary.is_file() {
        return Err(ServiceError::Invalid(format!(
            "service binary does not exist: {}",
            options.binary.display()
        )));
    }
    let unit = render_unit(&options.binary, &options.data_root)?;
    hieronymus::atomic::atomic_write_text(&options.unit_path(), &unit)?;
    lines.push(format!(
        "service unit written: {}",
        options.unit_path().display()
    ));
    if manager_enabled(options) {
        run_systemctl(&["daemon-reload"])?;
        run_systemctl(&["enable", SERVICE_UNIT_NAME])?;
        lines.push(format!(
            "service enabled (not started): {SERVICE_UNIT_NAME}"
        ));
    } else {
        lines.push(
            "manager integration skipped (custom --unit-dir or no systemctl on PATH); \
             enable/start it manually if needed"
                .to_string(),
        );
    }
    Ok(lines)
}

/// Remove the unit file only; databases, configuration, models, backups, and
/// audit data are never touched. Idempotent: a missing unit is a no-op.
pub fn uninstall(options: &ServiceOptions) -> Result<Vec<String>, ServiceError> {
    let mut lines = Vec::new();
    let path = options.unit_path();
    if path.exists() {
        std::fs::remove_file(&path)?;
        lines.push(format!("service unit removed: {}", path.display()));
    } else {
        lines.push("service unit already absent".to_string());
    }
    if manager_enabled(options) {
        run_systemctl(&["daemon-reload"])?;
        lines.push("manager reloaded".to_string());
    }
    Ok(lines)
}

/// What `hiero service status` reports.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceStatus {
    pub unit_path: PathBuf,
    pub definition: Option<UnitDefinition>,
    /// Why the definition is not consistent with these options, if it is not.
    pub problems: Vec<String>,
}

impl ServiceStatus {
    pub fn consistent(&self) -> bool {
        self.definition.is_some() && self.problems.is_empty()
    }

    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "unit": self.unit_path,
            "installed": self.definition.is_some(),
            "consistent": self.consistent(),
            "binary": self.definition.as_ref().map(|definition| definition.binary.clone()),
            "data_root": self.definition.as_ref().map(|definition| definition.data_root.clone()),
            "problems": self.problems,
        })
    }

    pub fn render_human(&self) -> String {
        match &self.definition {
            None => format!(
                "service unit: not installed ({} does not exist)",
                self.unit_path.display()
            ),
            Some(definition) => {
                let mut text = format!(
                    "service unit: {}\n  binary: {}\n  data root: {}",
                    self.unit_path.display(),
                    definition.binary.display(),
                    definition.data_root.display()
                );
                for problem in &self.problems {
                    text.push_str(&format!("\n  problem: {problem}"));
                }
                text
            }
        }
    }
}

/// Compare the installed unit against the expected definition.
pub fn status(options: &ServiceOptions) -> Result<ServiceStatus, ServiceError> {
    let definition = read_unit(options).map_err(ServiceError::Invalid)?;
    let mut problems = Vec::new();
    if let Some(definition) = &definition {
        if !definition.binary.is_file() {
            problems.push(format!(
                "unit binary does not exist: {}",
                definition.binary.display()
            ));
        }
        if definition.data_root != options.data_root {
            problems.push(format!(
                "unit serves data root {} but this root is {}",
                definition.data_root.display(),
                options.data_root.display()
            ));
        }
    }
    Ok(ServiceStatus {
        unit_path: options.unit_path(),
        definition,
        problems,
    })
}

/// Start or stop the daemon through the manager. Refuses (instead of
/// degrading) because an explicit lifecycle request that cannot be executed
/// must fail loudly, with the manual command in the message.
pub fn start(options: &ServiceOptions) -> Result<Vec<String>, ServiceError> {
    lifecycle(options, "start", &["start", SERVICE_UNIT_NAME])
}

pub fn stop(options: &ServiceOptions) -> Result<Vec<String>, ServiceError> {
    lifecycle(options, "stop", &["stop", SERVICE_UNIT_NAME])
}

/// Verdict of comparing the installed unit against the expected definition and
/// the currently running binary — doctor's service-definition check (security
/// spec §Service Installation).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UnitVerdict {
    Absent,
    Consistent,
    /// The unit is unreadable, is not one of ours, or its binary is gone.
    Broken(String),
    /// The unit serves a different data root than the one being checked.
    DataRootMismatch {
        unit_root: PathBuf,
    },
    /// The unit still execs a different binary than the running one (typical
    /// after an update that did not reinstall the unit).
    StaleBinary {
        unit_binary: PathBuf,
    },
}

/// Read the unit for `options` and compare it with `current_binary`.
pub fn check_unit(options: &ServiceOptions, current_binary: &Path) -> UnitVerdict {
    let definition = match read_unit(options) {
        Ok(Some(definition)) => definition,
        Ok(None) => return UnitVerdict::Absent,
        Err(reason) => return UnitVerdict::Broken(reason),
    };
    if !definition.binary.is_file() {
        return UnitVerdict::Broken(format!(
            "unit binary does not exist: {}",
            definition.binary.display()
        ));
    }
    if definition.data_root != options.data_root {
        return UnitVerdict::DataRootMismatch {
            unit_root: definition.data_root.clone(),
        };
    }
    let same_binary = match (
        definition.binary.canonicalize(),
        current_binary.canonicalize(),
    ) {
        (Ok(unit), Ok(current)) => unit == current,
        _ => definition.binary == current_binary,
    };
    if !same_binary {
        return UnitVerdict::StaleBinary {
            unit_binary: definition.binary.clone(),
        };
    }
    UnitVerdict::Consistent
}

fn lifecycle(
    options: &ServiceOptions,
    action: &str,
    arguments: &[&str],
) -> Result<Vec<String>, ServiceError> {
    if !options.unit_path().exists() {
        return Err(ServiceError::Manager(format!(
            "no service unit at {}; install one with `hiero service install`",
            options.unit_path().display()
        )));
    }
    if !manager_enabled(options) {
        return Err(ServiceError::Manager(format!(
            "manager integration is disabled for --unit-dir {}; {action} the daemon \
             manually: {} daemon --data-root {}",
            options.unit_dir.display(),
            options.binary.display(),
            options.data_root.display()
        )));
    }
    run_systemctl(arguments)?;
    Ok(vec![format!("service {action}ed: {SERVICE_UNIT_NAME}")])
}

#[cfg(test)]
mod tests {
    use super::*;

    fn options(temp: &tempfile::TempDir) -> ServiceOptions {
        ServiceOptions {
            data_root: temp.path().join("data"),
            unit_dir: temp.path().join("units"),
            binary: temp.path().join("bin/hiero"),
            use_manager: false,
        }
    }

    #[test]
    fn unit_renders_absolute_paths_and_the_restart_policy() {
        let unit = render_unit(
            Path::new("/opt/app/versions/1.0.0/hiero"),
            Path::new("/home/u/root"),
        )
        .unwrap();
        assert!(
            unit.contains(
                "ExecStart=\"/opt/app/versions/1.0.0/hiero\" daemon --data-root \"/home/u/root\""
            ),
            "{unit}"
        );
        assert!(unit.contains("Restart=on-failure"), "{unit}");
        assert!(unit.contains("RestartSec=5s"), "{unit}");
        assert!(unit.contains("WantedBy=default.target"), "{unit}");
        assert!(unit.contains("After=network.target"), "{unit}");
        assert!(
            unit.contains("SyslogIdentifier=hieronymus-daemon"),
            "{unit}"
        );
        assert!(unit.contains("NoNewPrivileges=true"), "{unit}");
    }

    #[test]
    fn unit_rendering_requires_absolute_supported_paths() {
        let error = render_unit(Path::new("relative/hiero"), Path::new("/root")).unwrap_err();
        assert!(error.to_string().contains("absolute"), "{error}");
        let error = render_unit(Path::new("/a\"b"), Path::new("/root")).unwrap_err();
        assert!(error.to_string().contains("quote"), "{error}");
    }

    #[test]
    fn unit_parses_back_into_its_definition() {
        let text = render_unit(Path::new("/opt/hiero"), Path::new("/root with space")).unwrap();
        let definition = parse_unit(&text).unwrap();
        assert_eq!(definition.binary, PathBuf::from("/opt/hiero"));
        assert_eq!(definition.data_root, PathBuf::from("/root with space"));
    }

    #[test]
    fn parse_rejects_foreign_units() {
        assert!(parse_unit("[Unit]\nDescription=x\n").is_err());
        assert!(parse_unit("ExecStart=/usr/bin/other --serve\n").is_err());
    }

    #[test]
    fn install_is_idempotent_and_never_contacts_the_manager_for_custom_unit_dirs() {
        let temp = tempfile::tempdir().unwrap();
        let options = options(&temp);
        std::fs::create_dir_all(options.binary.parent().unwrap()).unwrap();
        std::fs::write(&options.binary, b"fake binary").unwrap();

        let first = install(&options).unwrap();
        let second = install(&options).unwrap();
        assert!(
            first
                .iter()
                .any(|line| line.contains("manager integration skipped")),
            "{first:?}"
        );
        assert_eq!(
            std::fs::read_to_string(options.unit_path()).unwrap(),
            render_unit(&options.binary, &options.data_root).unwrap()
        );
        let _: Vec<String> = second;
    }

    #[test]
    fn install_refuses_a_missing_binary() {
        let temp = tempfile::tempdir().unwrap();
        let options = options(&temp);
        let error = install(&options).unwrap_err();
        assert!(error.to_string().contains("does not exist"), "{error}");
    }

    #[test]
    fn uninstall_removes_the_unit_and_is_idempotent() {
        let temp = tempfile::tempdir().unwrap();
        let options = options(&temp);
        std::fs::create_dir_all(&options.unit_dir).unwrap();
        std::fs::write(options.unit_path(), "[Unit]\n").unwrap();

        let lines = uninstall(&options).unwrap();
        assert!(lines[0].contains("removed"), "{lines:?}");
        assert!(!options.unit_path().exists());

        let lines = uninstall(&options).unwrap();
        assert!(lines[0].contains("already absent"), "{lines:?}");
    }

    #[test]
    fn status_reports_absent_broken_and_consistent_units() {
        let temp = tempfile::tempdir().unwrap();
        let options = options(&temp);
        std::fs::create_dir_all(options.binary.parent().unwrap()).unwrap();
        std::fs::write(&options.binary, b"binary").unwrap();

        // Absent.
        let absent = status(&options).unwrap();
        assert!(!absent.consistent());
        assert!(absent.render_human().contains("not installed"));

        // Consistent.
        install(&options).unwrap();
        let consistent = status(&options).unwrap();
        assert!(consistent.consistent(), "{consistent:?}");
        assert!(consistent.to_json()["installed"].as_bool().unwrap());

        // Broken: binary removed underneath the unit.
        std::fs::remove_file(&options.binary).unwrap();
        let broken = status(&options).unwrap();
        assert!(!broken.consistent());
        assert!(broken.problems[0].contains("does not exist"));

        // Mismatched data root.
        std::fs::write(&options.binary, b"binary").unwrap();
        let mut other = options.clone();
        other.data_root = temp.path().join("elsewhere");
        let mismatched = status(&other).unwrap();
        assert!(!mismatched.consistent());
        assert!(mismatched.problems[0].contains("data root"));
    }

    #[test]
    fn lifecycle_refuses_without_a_unit_and_without_manager_integration() {
        let temp = tempfile::tempdir().unwrap();
        let options = options(&temp);
        let error = start(&options).unwrap_err();
        assert!(error.to_string().contains("no service unit"), "{error}");

        std::fs::create_dir_all(&options.unit_dir).unwrap();
        std::fs::write(options.unit_path(), "[Unit]\n").unwrap();
        let error = stop(&options).unwrap_err();
        // Custom unit dir: the manager is never contacted.
        assert!(
            error
                .to_string()
                .contains("manager integration is disabled"),
            "{error}"
        );
    }

    #[test]
    fn unit_check_verdicts_cover_absent_consistent_broken_mismatch_and_stale() {
        let temp = tempfile::tempdir().unwrap();
        let options = options(&temp);
        std::fs::create_dir_all(options.binary.parent().unwrap()).unwrap();
        std::fs::write(&options.binary, b"binary").unwrap();
        let current_binary = options.binary.clone();

        // Absent.
        assert_eq!(check_unit(&options, &current_binary), UnitVerdict::Absent);

        // Consistent.
        install(&options).unwrap();
        assert_eq!(
            check_unit(&options, &current_binary),
            UnitVerdict::Consistent
        );

        // Broken: the unit's binary disappeared.
        std::fs::remove_file(&options.binary).unwrap();
        assert!(matches!(
            check_unit(&options, &current_binary),
            UnitVerdict::Broken(_)
        ));

        // Stale: a different (existing) binary than the running one.
        std::fs::write(&options.binary, b"binary").unwrap();
        let foreign = temp.path().join("foreign-hiero");
        std::fs::write(&foreign, b"foreign").unwrap();
        assert_eq!(
            check_unit(&options, &foreign),
            UnitVerdict::StaleBinary {
                unit_binary: options.binary.clone()
            }
        );

        // Mismatched data root.
        let mut other = options.clone();
        other.data_root = temp.path().join("elsewhere");
        assert_eq!(
            check_unit(&other, &current_binary),
            UnitVerdict::DataRootMismatch {
                unit_root: options.data_root.clone()
            }
        );
    }
}
