[package]
name = "hiero-bin"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "../../build.rs"

[[bin]]
name = "hiero"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
colored.workspace = true
hiero-core = { path = "../hiero-core" }
indicatif.workspace = true
mime_guess.workspace = true
rmcp.workspace = true
rust-embed.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
trycmd = "1.2"

[lints]
workspace = true
