[package]
name = "hiero-bin"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "../../build.rs"

[[bin]]
name = "hiero"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
colored.workspace = true
hiero-core = { path = "../hiero-core" }
indicatif.workspace = true
mime_guess.workspace = true
rmcp.workspace = true
rust-embed.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
sqlx.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
async-trait.workspace = true
assert_cmd = "2"
futures.workspace = true
insta = { version = "1", features = ["json"] }
predicates = "3"
tempfile.workspace = true
tokio-tungstenite.workspace = true
trycmd = "1.2"

[lints]
workspace = true
